### ISSUE TITLE
Collection of distinguished lecture notes

### ISSUE THREAD

**Issue by gallais** [scottish-pl-institute/scottish-pl-institute.github.io#2]
Now that they're happening, it'd be good to collect lecture notes and formalisations

**Comment by SimonJF** [comment]
We will most likely treat the distinguished lecture notes as "ad-hoc SPLI events" (like the industrial event), so each will have a dedicated page. The infrastructure is there now, so I think we can close this -- but feel free to reopen if it's insufficient or you had something else in mind.
