### ISSUE TITLE
Merge in SPLS-Series

### ISSUE THREAD

**Issue by jfdm** [scottish-pl-institute/scottish-pl-institute.github.io#3]
now that SPLI is up and running, would it make sense to fold in https://github.com/spls-series into the scottish-pl-institute organisation?

Specifically, only the SPLS website would need to be transferred to the scottish-pl-institute organisation, and, if setup correctly would appear under the following url:

https://scottish-pl-institute.github.io/spls

Similarly, #1 and #2 could be organised in a similar manner.

As for access control, this can be delegated via 'organisational teams', or on a per repo basis IIUC.

**Comment by liamoc** [comment]
I think this makes sense. Who has access to the SPLS-series organisation and can facilitate this? Is it @SimonJF ?

**Comment by slindley** [comment]
A number of people including me (and indeed @jfdm :)) have access. I've now invited you to join the SPLS organisation too.

**Comment by jfdm** [comment]
One thing to bear in mind is that HW are currently starting to organise SPLS Feb '23. So may be best to wait and fold things in post-event, or catch them now and do it pre-event.

**Comment by jfdm** [comment]
This has now been performed. I will close this issue once the remaining repo's from SPLS-Series have been brought over.

**Comment by jfdm** [comment]
Fixed, with #9 and creation of `scottish-pl-institute/spls` and `scottish-pl-institute/spls-organisation`.
